name: Fertiscan pipeline workflows

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  lint-test:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-lint-test-python.yml@main
    secrets: inherit

  markdown-check:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@main
    secrets: inherit

  repo-standard:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    secrets: inherit

  pyproject-version-bump:
    if: github.event.pull_request.merged != true
    name: fertiscan-pipeline-pyproject-version-bump
    uses: ai-cfia/github-workflows/.github/workflows/workflow-version-bump-python.yml@main
    secrets: inherit

  trigger-release:
    if: github.event.pull_request.merged == true
    uses: ai-cfia/github-workflows/.github/workflows/workflow-pyproject-release.yml@main
    secrets: inherit
